# Generated by Django 4.1.13 on 2024-03-20 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_conversation_message_delete_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='type',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
