# Generated by Django 4.1.13 on 2024-04-14 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_message_file_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='agent',
            field=models.CharField(default='bot', max_length=100),
            preserve_default=False,
        ),
    ]
